const products = [
    {
      name: "The Classic Tee",
      description: "A comfortable and versatile t-shirt for everyday wear.",
      price: 25.00,
      imageUrl: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "White", "Gray", "Navy"],
    },
    {
      name: "Cozy Knit Sweater",
      description: "Stay warm and stylish in this soft knit sweater.",
      price: 60.00,
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREN07kYhTvWA4urHXRu6mJq-6JTOMFBJbwjA&s",
      sizes: ["S", "M", "L"],
      colors: ["Cream", "Brown", "Burgundy"],
    },
    {
      name: "Relaxed Fit Jeans",
      description: "Comfortable and durable jeans with a relaxed fit.",
      price: 75.00,
      imageUrl: "https://www.cernucci.com/cdn/shop/files/HP-MARMOTK23DH-OW_VG-NVRD01DH-M-VB-5.jpg?v=1721658538&width=1024",
      sizes: ["28", "30", "32", "34", "36"],
      colors: ["Blue", "Black", "Gray"],
    },
    {
      name: "Stylish Leather Jacket",
      description: "A classic leather jacket that will never go out of style.",
      price: 250.00,
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQUv8VxNnQIbNBYC7Q0yzObbRDOlju72JkZeg&s",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "Brown"],
    },
    {
      name: "Sporty Running Shoes",
      description: "Lightweight and comfortable running shoes for optimal performance.",
      price: 90.00,
      imageUrl: "https://5.imimg.com/data5/LI/CR/NO/SELLER-91747408/nike-sports-running-shoes.jpg",
      sizes: ["7", "8", "9", "10", "11", "12"],
      colors: ["Blue", "Red", "Gray", "Black"],
    },
    {
      name: "Waterproof Hiking Boots",
      description: "Durable and waterproof hiking boots for outdoor adventures.",
      price: 120.00,
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgMxy_q8lhSL6d7pGhFRe_MyNBfLf_DfJTXQ&s",
      sizes: ["7", "8", "9", "10", "11", "12"],
      colors: ["Brown", "Black"],
    },
    {
      name: "Cotton Button-Down Shirt",
      description: "A versatile cotton button-down shirt for a polished look.",
      price: 45.00,
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTx6IYvze4MmsRgBz8z0j_gEqr1iWeuRxsaaw&s",
      sizes: ["S", "M", "L", "XL"],
      colors: ["White", "Blue", "Gray", "Striped"],
    },
    {
      name: "Warm Winter Coat",
      description: "A heavy-duty winter coat to keep you warm in the coldest weather.",
      price: 180.00,
      imageUrl: "https://i.ebayimg.com/images/g/c0IAAOSwdUVdGXvQ/s-l400.jpg",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "Navy", "Gray"],
    },
    {
      name: "Casual Sneakers",
      description: "Comfortable and stylish sneakers for everyday wear.",
      price: 65.00,
      imageUrl: "https://images.unsplash.com/photo-1527091827858-884438176b23?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
      sizes: ["7", "8", "9", "10", "11", "12"],
      colors: ["White", "Black", "Red", "Blue"],
    },
     {
      name: "Striped Breton Top",
      description: "A classic striped top for a timeless look.",
      price: 35.00,
      imageUrl: "https://images.unsplash.com/photo-1616379008074-ca5799f23530?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80",
      sizes: ["XS", "S", "M", "L", "XL"],
      colors: ["Navy/White", "Black/White", "Red/White"],
    },
    {
      name: "Chino Shorts",
      description: "Versatile chino shorts, perfect for warmer weather.",
      price: 40.00,
      imageUrl: "https://images.unsplash.com/photo-1617159422304-ef7c63a00609?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
      sizes: ["28", "30", "32", "34", "36"],
      colors: ["Beige", "Navy", "Olive"],
    },
    {
      name: "Cashmere Scarf",
      description: "A luxurious and soft cashmere scarf for added warmth.",
      price: 85.00,
      imageUrl: "https://images.unsplash.com/photo-1597582763578-c24313d3d641?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
      sizes: ["One Size"],
      colors: ["Gray", "Black", "Red", "Blue", "Purple"],
    },
    {
      name: "Denim Jacket",
      description: "A classic denim jacket, perfect for layering.",
      price: 80.00,
      imageUrl: "https://images.unsplash.com/photo-1605405885285-964704a0ca5e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Blue", "Black", "White"],
    },
    {
      name: "Leather Belt",
      description: "A stylish and durable leather belt.",
      price: 30.00,
      imageUrl: "https://images.unsplash.com/photo-1610853495282-b10ca175e439?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
      sizes: ["30", "32", "34", "36", "38"],
      colors: ["Brown", "Black"],
    },
    {
      name: "Summer Sundress",
      description: "A lightweight and breezy sundress perfect for hot days.",
      price: 55.00,
      imageUrl: "https://images.unsplash.com/photo-1584066158262-d0c971759528?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
      sizes: ["XS", "S", "M", "L"],
      colors: ["Floral", "Yellow", "Blue", "Pink"],
    },
    {
      name: "Work Backpack",
      description: "A durable backpack with dedicated laptop and tablet compartments.",
      price: 95.00,
      imageUrl: "https://images.unsplash.com/photo-1553060937-5d2d74482c22?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
      sizes: ["One Size"],
      colors: ["Black", "Gray", "Navy"],
    },
     {
      name: "Baseball Cap",
      description: "Classic baseball cap to shield you from the sun.",
      price: 20.00,
      imageUrl: "https://images.unsplash.com/photo-1505700490543-a6a21600b951?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
      sizes: ["One Size"],
      colors: ["Black", "Navy", "Red", "White"],
    },
    {
      name: "Ankle Boots",
      description: "Stylish and versatile ankle boots for any occasion.",
      price: 110.00,
      imageUrl: "https://images.unsplash.com/photo-1616294634004-812475453dbf?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
      sizes: ["6", "7", "8", "9", "10"],
      colors: ["Black", "Brown", "Beige"],
    },
    {
      name: "Tracksuit",
      description: "A comfortable and sporty tracksuit for lounging or working out.",
      price: 90.00,
      imageUrl: "https://images.unsplash.com/photo-1610645194613-438f707a1057?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Black", "Gray", "Navy", "Red"],
    },
    {
      name: "Pencil Skirt",
      description: "A sophisticated and flattering pencil skirt for office or evening wear.",
      price: 50.00,
      imageUrl: "https://images.unsplash.com/photo-1590974198295-f6a920f6d175?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
      sizes: ["XS", "S", "M", "L"],
      colors: ["Black", "Navy", "Gray", "Burgundy"],
    },
    {
      name: "Wool Socks",
      description: "Cozy and warm wool socks for cold days.",
      price: 15.00,
      imageUrl: "https://www.nepacrafts.com/cdn/shop/files/7cb7477a-7137-52f3-bb8d-5bd05839a520_512x727.png?v=1729590982",
      sizes: ["One Size"],
      colors: ["Gray", "Black", "Navy", "Brown", "Cream"],
    },
     {
      name: "Oversized Hoodie",
      description: "Super comfortable and oversized hoodie for ultimate relaxation.",
      price: 55.00,
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtgtNFk_WbzayNHPU2WkZ9N0MiiGjsLVC5Fw&s",
      sizes: ["S", "M", "L", "XL"],
      colors: ["Gray", "Black", "Pink", "Blue"],
    },
    {
      name: "Yoga Pants",
      description: "Comfortable and stretchy yoga pants for workouts or everyday wear.",
      price: 45.00,
      imageUrl: "https://www.wearetala.com/cdn/shop/files/Dayflex_wrapflareyogapant_Black_1_228.jpg?v=1723111440",
      sizes: ["XS", "S", "M", "L"],
      colors: ["Black", "Navy", "Gray", "Purple"],
    },
    {
      name: "Beanie",
      description: "A warm and stylish beanie for winter.",
      price: 22.00,
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIYxoPWtcsEpSswt1BwGjCNL6bl2m2n3Dbxg&s",
      sizes: ["One Size"],
      colors: ["Black", "Gray", "Navy", "Red", "Green"],
    },
  
    {
      name: "Bucket Hat",
      description: "A stylish and versatile bucket hat for sunny days.",
      price: 28.00,
      imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFeBNPIJiYtd9i_PAcVArLrIBDVxBJvyV9_w&s",
      sizes: ["One Size"],
      colors: ["Black", "White", "Beige", "Floral"],
    },
  ];
  
  module.exports = {data:products};